### ISSUE TITLE
xpkg build failure in github actions

### ISSUE THREAD

**Issue by darkmuggle** [upbound/build#244]
### What happened?
```
crossplane CLI downloaded successfully! Run the following commands to finish installing it:

sudo mv crossplane /usr/local/bin
crossplane --help

Visit https://crossplane.io/ to get started. 🚀
Have a nice day! 👋

Run ./crossplane build configuration -f /home/runner/work/platform-composites/platform-composites/package --name package.xpkg
  ./crossplane build configuration -f /home/runner/work/platform-composites/platform-composites/package --name package.xpkg
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    DOCKER_USR: ***
    PACKAGE_NAME: upbound/platform-composites
crossplane: error: unexpected argument build
Usage: crossplane <command>

A command line tool for interacting with Crossplane.

Commands:
  xpkg build        Build a new package.
  xpkg install      Install a package in a control plane.
  xpkg login        Login to the default package registry.
  xpkg logout       Logout of the default package registry.
  xpkg push         Push a package to a registry.
  xpkg update       Update a package in a control plane.
  beta render       Render a composite resource (XR).
  beta trace        Trace a Crossplane resource to get a detailed output of its
                    relationships, helpful for troubleshooting.
  beta xpkg init    Initialize a new package from a template.

Flags:
  -h, --help       Show context-sensitive help.
      --verbose    Print verbose logging statements.
  -v, --version    Print version and quit.

Run "crossplane <command> --help" for more information on a command.
```

**Comment by phisco** [comment]
Can you add a bit more context? Are you using https://github.com/crossplane-contrib/xpkg-action? If so what configuration are you using?

**Comment by ldalorion** [comment]
This ticket should have gone under crossplane/crossplane but here's the build steps that is failing for us. 
```yaml
      - name: Build
        uses: crossplane-contrib/xpkg-action@master
        with:
          channel: stable
          version: current
          command: build configuration -f ${{ github.workspace }}/package --name package.xpkg
```
